spring.application.name=PlacementManagementSystem

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${DB_URL:jdbc:mysql://switchyard.proxy.rlwy.net:34768/railway}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MevnVaCWMzLdREQhNkOYBKeXEpZDxDcA}
server.port=${PORT:8080}

#hibernate properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=snehavakkalagadda@gmail.com
spring.mail.password=gtbg nxtd lpei unfm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true